global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'MarketMaker2'

    basic_auth:
      username: 'PROM_USERNAME'
      password: "PROM_PASSWORD"

    static_configs:
      - targets: ['0.0.0.0:9001']

